Write a Python program using Pandas to create a DataFrame from the given data and calculate the average rating of movies directed by Christopher Nolan.

In [15]:
import pandas as pd 
data = {
    'Title': ['Inception', 'Dunkirk', 'Interstellar', 'The Prestige', 'Memento'],
    'Director': ['Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan'],
    'Rating': [8.8, 7.9, 8.6, 8.5, 8.4]
}

df=pd.DataFrame(data)
#df.head()
#average rating of movies directed by Christopher Nolan
print(df.groupby('Director')['Rating'].mean())
print(df.groupby('Director')['Rating'].mean().values)
print(df.groupby('Director')['Rating'].mean().loc['Christopher Nolan'])

nolan_movies = df[df['Director'] == 'Christopher Nolan']
average_rating = nolan_movies['Rating'].mean()
print("Average Rating of Christopher Nolan's movies:", average_rating)

Director
Christopher Nolan    8.44
Name: Rating, dtype: float64
[8.44]
8.440000000000001
Average Rating of Christopher Nolan's movies: 8.440000000000001

Given the following DataFrame, write a Python program using Pandas to extract all rows where the price is greater than or equal to 20,000 and sort them in descending order by price.

In [21]:
data = {
    'Product': ['Laptop', 'Desktop', 'Tablet', 'Phone', 'Smartwatch'],
    'Price': [25000, 12000, 8000, 22000, 5000]
}
df = pd.DataFrame(data)
df.head()
#rows where the price is greater than or equal to 20,000 
df[df['Price']>=20000].sort_values('Price',ascending=False)

  Product  Price
0  Laptop  25000
3   Phone  22000

Write a Python program using Pandas to create a DataFrame from the given data and find the total revenue and average price of items sold in each store.

In [39]:
data = {
    'Store': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Item': ['Apple', 'Banana', 'Orange', 'Grape', 'Apple', 'Banana', 'Orange', 'Grape'],
    'Price': [50, 20, 30, 60, 55, 22, 33, 65],
    'Quantity': [10, 12, 15, 16, 20, 25, 30, 35]
}
df = pd.DataFrame(data)
print(df.head())
#find the total revenue and average price of items sold in each store
df['Revenue']=df['Price']*df['Quantity']
print(df.groupby('Store')['Revenue'].sum(),df.groupby('Store')['Price'].mean())
#Better way
filtered_df=df.groupby('Store').agg({'Revenue':'sum', 'Price': 'mean'}).reset_index()
filtered_df.rename(columns={'Price': 'Avg Price'},inplace=True)
print(filtered_df)

  Store    Item  Price  Quantity
0     A   Apple     50        10
1     B  Banana     20        12
2     A  Orange     30        15
3     B   Grape     60        16
4     A   Apple     55        20
Store
A    3040
B    4025
Name: Revenue, dtype: int64 Store
A    42.00
B    41.75
Name: Price, dtype: float64
  Store  Revenue  Avg Price
0     A     3040      42.00
1     B     4025      41.75

Write a Python program using Pandas to create a DataFrame from the given data and calculate the total amount spent by each customer.

In [48]:
data = {
    'Customer': ['Alice', 'Bob', 'Alice', 'Alice', 'Bob', 'Bob', 'Alice', 'Bob'],
    'Item': ['Pen', 'Pencil', 'Notebook', 'Eraser', 'Pen', 'Pencil', 'Notebook', 'Eraser'],
    'Price': [10, 5, 50, 20, 10, 5, 50, 20],
    'Quantity': [3, 4, 2, 5, 10, 6, 1, 2]
}

df=pd.DataFrame(data)
df['Total']=df['Price']*df['Quantity']
print(df.head())
df.groupby('Customer')['Total'].sum().reset_index()

  Customer      Item  Price  Quantity  Total
0    Alice       Pen     10         3     30
1      Bob    Pencil      5         4     20
2    Alice  Notebook     50         2    100
3    Alice    Eraser     20         5    100
4      Bob       Pen     10        10    100

  Customer  Total
0    Alice    280
1      Bob    190

Write a Python program using Pandas to create a DataFrame from the given data and find the month with the highest average temperature.

In [67]:
data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    'Temperature': [20, 22, 25, 27, 30, 32, 35, 34, 30, 28, 24, 21]
}
df = pd.DataFrame(data)
print(df.head())
#Just get teh max temperature
df.Temperature.max()
#To get the month with max temperature 
highest_avg_temp_month = df.loc[df['Temperature'].idxmax()]['Month']
print("Month with the highest average temperature:", highest_avg_temp_month)
#Alternate method
df.loc[df['Temperature']==int(df.Temperature.max())]['Month']

  Month  Temperature
0   Jan           20
1   Feb           22
2   Mar           25
3   Apr           27
4   May           30
Month with the highest average temperature: Jul

6    Jul
Name: Month, dtype: str

Given the following DataFrame and code snippet, predict the output of the code.

In [69]:

data = {
    'Category': ['Fruit', 'Vegetable', 'Fruit', 'Vegetable', 'Fruit', 'Vegetable'],
    'Name': ['Apple', 'Carrot', 'Banana', 'Potato', 'Grape', 'Onion'],
    'Price': [2, 1, 1.5, 0.5, 3, 1],
    'Quantity': [10, 20, 15, 30, 5, 40]
}
df = pd.DataFrame(data)
fruits = df[df['Category'] == 'Fruit']
fruits
total_fruit_value = fruits['Price'].sum() * fruits['Quantity'].sum()

print(total_fruit_value) #6.5*30 =195

195.0

Given the following DataFrame and code snippet, predict the output of the code.

In [70]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
result = df[df['Age'] >= 30].sort_values(by='Age', ascending=False).iloc[0]['City']
print(result)

Chicago

Given the following DataFrame and code snippet, predict the output of the code.

In [71]:
data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C'],
    'Price': [100, 200, 300, 150, 250, 350],
    'Quantity': [10, 5, 7, 12, 8, 5]
}
df = pd.DataFrame(data)
total_revenue = (df['Price'] * df['Quantity']).sum()
average_price = df['Price'].mean() #1350/6 =225
print(total_revenue, average_price) #

9650 225.0

Write a Python program using Pandas to create a DataFrame from the given data and find the total amount spent per item, as well as the total amount spent by all customers.

In [74]:
data = {
    'Customer': ['Alice', 'Bob', 'Alice', 'Alice', 'Bob', 'Bob', 'Alice', 'Bob'],
    'Item': ['Pen', 'Pencil', 'Notebook', 'Eraser', 'Pen', 'Pencil', 'Notebook', 'Eraser'],
    'Price': [10, 5, 50, 20, 10, 5, 50, 20],
    'Quantity': [3, 4, 2, 5, 10, 6, 1, 2]
}
df=pd.DataFrame(data)
df['Total']=df['Price']*df['Quantity']
print(df.groupby('Customer').agg({'Total':'sum'}).reset_index())
print(df['Total'].sum())

  Customer  Total
0    Alice    280
1      Bob    190
470

 Write a Python program using Pandas to create a DataFrame from the given data and calculate the monthly average temperature difference between two cities.

In [81]:
data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    'City_A_Temp': [20, 22, 25, 27, 30, 32, 35, 34, 30, 28, 24, 21],
    'City_B_Temp': [10, 12, 15, 17, 20, 22, 25, 24, 20, 18, 14, 11]
}
df = pd.DataFrame(data)
#df[['City_A_Temp','City_B_Temp']]
df['Temp Diff']=df[['City_A_Temp','City_B_Temp']].apply(lambda row:abs(row['City_A_Temp']-row['City_B_Temp']),axis=1)
print(df.head())

  Month  City_A_Temp  City_B_Temp  Temp Diff
0   Jan           20           10         10
1   Feb           22           12         10
2   Mar           25           15         10
3   Apr           27           17         10
4   May           30           20         10